name: CI

on:
- push
- pull_request

env:
  CI: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Qmake
      run: qmake
    - name: ls
      run: ls -la
    - name: make
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: project.exe
