name: CI

on:
- push
- pull_request

env:
  CI: true
  YARN_ENABLE_IMMUTABLE_INSTALLS: 'false'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Config And Install
      run: qmake && make
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: project.exe
