name: CI

on:
- push
- pull_request

env:
  CI: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Run vcvars
      run: |
        call "%programfiles%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
        ls %programfiles(x86)%
        echo 1
        ls %programfiles%
        echo 2
        ls "%programfiles%\Microsoft Visual Studio"
        echo 3
        ls "%programfiles%\Microsoft Visual Studio\2019"
        echo 4
        ls "%programfiles(x86)%\Microsoft Visual Studio"
        qmake
        make
      shell: cmd
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: project.exe
